package log;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
public class KeyBD extends javax.swing.JFrame {

    /**
     * Creates new form KeyBD
     */
    public KeyBD() {
    initComponents();
    setLocationRelativeTo(null);  
     setIconImage(new ImageIcon("C:\\Users\\THE BOY\\Desktop\\YAO\\Church Managements System\\src\\Image\\download (1).jpg").getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnA = new javax.swing.JButton();
        jABC = new javax.swing.JTextField();
        btnB = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btnD = new javax.swing.JButton();
        btnE = new javax.swing.JButton();
        btnF = new javax.swing.JButton();
        btnG = new javax.swing.JButton();
        btnH = new javax.swing.JButton();
        btnI = new javax.swing.JButton();
        btnJ = new javax.swing.JButton();
        btnK = new javax.swing.JButton();
        btnL = new javax.swing.JButton();
        btnM = new javax.swing.JButton();
        btnN = new javax.swing.JButton();
        btnO = new javax.swing.JButton();
        btnP = new javax.swing.JButton();
        btnQ = new javax.swing.JButton();
        btnR = new javax.swing.JButton();
        btnS = new javax.swing.JButton();
        btnT = new javax.swing.JButton();
        btnU = new javax.swing.JButton();
        btnV = new javax.swing.JButton();
        btnW = new javax.swing.JButton();
        btnX = new javax.swing.JButton();
        btnY = new javax.swing.JButton();
        btnZ = new javax.swing.JButton();
        btnZERO = new javax.swing.JButton();
        btnONE = new javax.swing.JButton();
        btnTWO = new javax.swing.JButton();
        btnTHREE = new javax.swing.JButton();
        btnFOUR = new javax.swing.JButton();
        btnFIVE = new javax.swing.JButton();
        btnSIX = new javax.swing.JButton();
        btnSEVEN = new javax.swing.JButton();
        btnEIGHT = new javax.swing.JButton();
        btnNINE = new javax.swing.JButton();
        btnSPACE = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnDELETE = new javax.swing.JButton();
        btnBSPACE = new javax.swing.JButton();
        btnDOT = new javax.swing.JButton();
        btnOFF = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnA.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnA.setText("A");
        btnA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAActionPerformed(evt);
            }
        });
        getContentPane().add(btnA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jABC.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jABC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jABCActionPerformed(evt);
            }
        });
        getContentPane().add(jABC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 840, 50));

        btnB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnB.setText("B");
        btnB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBActionPerformed(evt);
            }
        });
        getContentPane().add(btnB, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, -1));

        btnC.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnC.setText("C");
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });
        getContentPane().add(btnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        btnD.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnD.setText("D");
        btnD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDActionPerformed(evt);
            }
        });
        getContentPane().add(btnD, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        btnE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnE.setText("E");
        btnE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEActionPerformed(evt);
            }
        });
        getContentPane().add(btnE, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        btnF.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnF.setText("F");
        btnF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFActionPerformed(evt);
            }
        });
        getContentPane().add(btnF, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, -1));

        btnG.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnG.setText("G");
        btnG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGActionPerformed(evt);
            }
        });
        getContentPane().add(btnG, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, -1));

        btnH.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnH.setText("H");
        btnH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHActionPerformed(evt);
            }
        });
        getContentPane().add(btnH, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));

        btnI.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnI.setText("I");
        btnI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIActionPerformed(evt);
            }
        });
        getContentPane().add(btnI, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, -1, -1));

        btnJ.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnJ.setText("J");
        btnJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJActionPerformed(evt);
            }
        });
        getContentPane().add(btnJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, -1, -1));

        btnK.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnK.setText("K");
        btnK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKActionPerformed(evt);
            }
        });
        getContentPane().add(btnK, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, -1, -1));

        btnL.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnL.setText("L");
        btnL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLActionPerformed(evt);
            }
        });
        getContentPane().add(btnL, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, -1, -1));

        btnM.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnM.setText("M");
        btnM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMActionPerformed(evt);
            }
        });
        getContentPane().add(btnM, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, -1, -1));

        btnN.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnN.setText("N");
        btnN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNActionPerformed(evt);
            }
        });
        getContentPane().add(btnN, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, -1, -1));

        btnO.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnO.setText("O");
        btnO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOActionPerformed(evt);
            }
        });
        getContentPane().add(btnO, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, -1, -1));

        btnP.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnP.setText("P");
        btnP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPActionPerformed(evt);
            }
        });
        getContentPane().add(btnP, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, -1, -1));

        btnQ.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnQ.setText("Q");
        btnQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQActionPerformed(evt);
            }
        });
        getContentPane().add(btnQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        btnR.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnR.setText("R");
        btnR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRActionPerformed(evt);
            }
        });
        getContentPane().add(btnR, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));

        btnS.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnS.setText("S");
        btnS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSActionPerformed(evt);
            }
        });
        getContentPane().add(btnS, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        btnT.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnT.setText("T");
        btnT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTActionPerformed(evt);
            }
        });
        getContentPane().add(btnT, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, -1));

        btnU.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnU.setText("U");
        btnU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUActionPerformed(evt);
            }
        });
        getContentPane().add(btnU, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, -1));

        btnV.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnV.setText("V");
        btnV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVActionPerformed(evt);
            }
        });
        getContentPane().add(btnV, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        btnW.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnW.setText("W");
        btnW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWActionPerformed(evt);
            }
        });
        getContentPane().add(btnW, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        btnX.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnX.setText("X");
        btnX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXActionPerformed(evt);
            }
        });
        getContentPane().add(btnX, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        btnY.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnY.setText("Y");
        btnY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYActionPerformed(evt);
            }
        });
        getContentPane().add(btnY, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, -1, -1));

        btnZ.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnZ.setText("Z");
        btnZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZActionPerformed(evt);
            }
        });
        getContentPane().add(btnZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        btnZERO.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnZERO.setText("0");
        btnZERO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZEROActionPerformed(evt);
            }
        });
        getContentPane().add(btnZERO, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 220, -1, -1));

        btnONE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnONE.setText("1");
        btnONE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnONEActionPerformed(evt);
            }
        });
        getContentPane().add(btnONE, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, -1, -1));

        btnTWO.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnTWO.setText("2");
        btnTWO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTWOActionPerformed(evt);
            }
        });
        getContentPane().add(btnTWO, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 170, -1, -1));

        btnTHREE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnTHREE.setText("3");
        btnTHREE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTHREEActionPerformed(evt);
            }
        });
        getContentPane().add(btnTHREE, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 170, -1, -1));

        btnFOUR.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnFOUR.setText("4");
        btnFOUR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFOURActionPerformed(evt);
            }
        });
        getContentPane().add(btnFOUR, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, -1, -1));

        btnFIVE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnFIVE.setText("5");
        btnFIVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFIVEActionPerformed(evt);
            }
        });
        getContentPane().add(btnFIVE, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 120, -1, -1));

        btnSIX.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnSIX.setText("6");
        btnSIX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSIXActionPerformed(evt);
            }
        });
        getContentPane().add(btnSIX, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 120, -1, -1));

        btnSEVEN.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnSEVEN.setText("7");
        btnSEVEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSEVENActionPerformed(evt);
            }
        });
        getContentPane().add(btnSEVEN, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 70, -1, -1));

        btnEIGHT.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnEIGHT.setText("8");
        btnEIGHT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEIGHTActionPerformed(evt);
            }
        });
        getContentPane().add(btnEIGHT, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 70, -1, -1));

        btnNINE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnNINE.setText("9");
        btnNINE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNINEActionPerformed(evt);
            }
        });
        getContentPane().add(btnNINE, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 70, -1, -1));

        btnSPACE.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSPACE.setText("SPACE");
        btnSPACE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSPACEActionPerformed(evt);
            }
        });
        getContentPane().add(btnSPACE, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 180, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Created By Azameti Yao Charles.© Copyright Protected ®™ 2018");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 430, 20));

        btnDELETE.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDELETE.setText("Delete");
        btnDELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDELETEActionPerformed(evt);
            }
        });
        getContentPane().add(btnDELETE, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 90, 40));

        btnBSPACE.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBSPACE.setText("Back Space");
        getContentPane().add(btnBSPACE, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 130, 40));

        btnDOT.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnDOT.setText(".");
        btnDOT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDOTActionPerformed(evt);
            }
        });
        getContentPane().add(btnDOT, new org.netbeans.lib.awtextra.AbsoluteConstraints(683, 220, 40, 40));

        btnOFF.setBackground(new java.awt.Color(255, 0, 0));
        btnOFF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnOFF.setForeground(new java.awt.Color(51, 51, 255));
        btnOFF.setText("OFF");
        btnOFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOFFActionPerformed(evt);
            }
        });
        getContentPane().add(btnOFF, new org.netbeans.lib.awtextra.AbsoluteConstraints(793, 220, -1, 40));

        jLabel1.setBackground(new java.awt.Color(153, 204, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 204, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/Desert.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 415));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jABCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jABCActionPerformed
jABC.setText("null");
        // TODO add your handling code here:
    }//GEN-LAST:event_jABCActionPerformed

    private void btnAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAActionPerformed
jABC.setText(jABC.getText().concat("A"));
    }//GEN-LAST:event_btnAActionPerformed

    private void btnBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBActionPerformed
jABC.setText(jABC.getText().concat("B"));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBActionPerformed

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
jABC.setText(jABC.getText().concat("C"));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCActionPerformed

    private void btnDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDActionPerformed
      jABC.setText(jABC.getText().concat("D"));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDActionPerformed

    private void btnEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEActionPerformed
jABC.setText(jABC.getText().concat("E"));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEActionPerformed

    private void btnFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFActionPerformed
jABC.setText(jABC.getText().concat("F"));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFActionPerformed

    private void btnGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGActionPerformed
jABC.setText(jABC.getText().concat("G"));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGActionPerformed

    private void btnHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHActionPerformed
jABC.setText(jABC.getText().concat("H"));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHActionPerformed

    private void btnIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIActionPerformed
jABC.setText(jABC.getText().concat("I"));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIActionPerformed

    private void btnJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJActionPerformed
jABC.setText(jABC.getText().concat("J"));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnJActionPerformed

    private void btnKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKActionPerformed
jABC.setText(jABC.getText().concat("K"));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKActionPerformed

    private void btnLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLActionPerformed
jABC.setText(jABC.getText().concat("L"));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLActionPerformed

    private void btnWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWActionPerformed
jABC.setText(jABC.getText().concat("W"));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnWActionPerformed

    private void btnQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQActionPerformed
jABC.setText(jABC.getText().concat("Q"));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQActionPerformed

    private void btnRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRActionPerformed
jABC.setText(jABC.getText().concat("R"));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRActionPerformed

    private void btnTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTActionPerformed
jABC.setText(jABC.getText().concat("T"));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTActionPerformed

    private void btnYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYActionPerformed
jABC.setText(jABC.getText().concat("Y"));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnYActionPerformed

    private void btnUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUActionPerformed
jABC.setText(jABC.getText().concat("U"));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUActionPerformed

    private void btnOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOActionPerformed
jABC.setText(jABC.getText().concat("O"));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOActionPerformed

    private void btnPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPActionPerformed
jABC.setText(jABC.getText().concat("P"));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPActionPerformed

    private void btnSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSActionPerformed
jABC.setText(jABC.getText().concat("S"));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSActionPerformed

    private void btnZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZActionPerformed
jABC.setText(jABC.getText().concat("Z"));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnZActionPerformed

    private void btnXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXActionPerformed
jABC.setText(jABC.getText().concat("X"));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXActionPerformed

    private void btnVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVActionPerformed
jABC.setText(jABC.getText().concat("V"));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVActionPerformed

    private void btnMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMActionPerformed
jABC.setText(jABC.getText().concat("M"));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMActionPerformed

    private void btnNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNActionPerformed
    jABC.setText(jABC.getText().concat("N"));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNActionPerformed

    private void btnSEVENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSEVENActionPerformed
jABC.setText(jABC.getText().concat("7"));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSEVENActionPerformed

    private void btnEIGHTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEIGHTActionPerformed
jABC.setText(jABC.getText().concat("8"));     
// TODO add your handling code here:
    }//GEN-LAST:event_btnEIGHTActionPerformed

    private void btnNINEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNINEActionPerformed
jABC.setText(jABC.getText().concat("9"));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNINEActionPerformed

    private void btnFOURActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFOURActionPerformed
jABC.setText(jABC.getText().concat("4"));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFOURActionPerformed

    private void btnFIVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFIVEActionPerformed
jABC.setText(jABC.getText().concat("5"));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFIVEActionPerformed

    private void btnSIXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSIXActionPerformed
jABC.setText(jABC.getText().concat("6"));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSIXActionPerformed

    private void btnONEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnONEActionPerformed
jABC.setText(jABC.getText().concat("1"));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnONEActionPerformed

    private void btnTWOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTWOActionPerformed
jABC.setText(jABC.getText().concat("2"));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTWOActionPerformed

    private void btnTHREEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTHREEActionPerformed
jABC.setText(jABC.getText().concat("3"));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTHREEActionPerformed

    private void btnZEROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZEROActionPerformed
jABC.setText(jABC.getText().concat("0"));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnZEROActionPerformed

    private void btnSPACEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSPACEActionPerformed
jABC.setText(jABC.getText().concat(" "));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSPACEActionPerformed

    private void btnDELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDELETEActionPerformed
jABC.setText(" ");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDELETEActionPerformed

    private void btnDOTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDOTActionPerformed
jABC.setText(jABC.getText().concat("."));
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDOTActionPerformed

    private void btnOFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOFFActionPerformed
  int saints = JOptionPane.showConfirmDialog(null, "Do You Want To Exit The program?");
            boolean Yes = saints==JOptionPane.OK_OPTION;
            //JOptionPane.showConfirmDialog(null, "GOOD BYE!!");//
                   dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOFFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KeyBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KeyBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KeyBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KeyBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
 UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KeyBD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnA;
    private javax.swing.JButton btnB;
    private javax.swing.JButton btnBSPACE;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnD;
    private javax.swing.JButton btnDELETE;
    private javax.swing.JButton btnDOT;
    private javax.swing.JButton btnE;
    private javax.swing.JButton btnEIGHT;
    private javax.swing.JButton btnF;
    private javax.swing.JButton btnFIVE;
    private javax.swing.JButton btnFOUR;
    private javax.swing.JButton btnG;
    private javax.swing.JButton btnH;
    private javax.swing.JButton btnI;
    private javax.swing.JButton btnJ;
    private javax.swing.JButton btnK;
    private javax.swing.JButton btnL;
    private javax.swing.JButton btnM;
    private javax.swing.JButton btnN;
    private javax.swing.JButton btnNINE;
    private javax.swing.JButton btnO;
    private javax.swing.JButton btnOFF;
    private javax.swing.JButton btnONE;
    private javax.swing.JButton btnP;
    private javax.swing.JButton btnQ;
    private javax.swing.JButton btnR;
    private javax.swing.JButton btnS;
    private javax.swing.JButton btnSEVEN;
    private javax.swing.JButton btnSIX;
    private javax.swing.JButton btnSPACE;
    private javax.swing.JButton btnT;
    private javax.swing.JButton btnTHREE;
    private javax.swing.JButton btnTWO;
    private javax.swing.JButton btnU;
    private javax.swing.JButton btnV;
    private javax.swing.JButton btnW;
    private javax.swing.JButton btnX;
    private javax.swing.JButton btnY;
    private javax.swing.JButton btnZ;
    private javax.swing.JButton btnZERO;
    private javax.swing.JTextField jABC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
