/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package log;


import javax.swing.ImageIcon;
import java.text.DateFormat; 
import java.text.SimpleDateFormat; 
import java.util.Calendar; 
import java.util.Date;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import static java.lang.Thread.sleep;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author EstyLand
 */

public class Mains extends javax.swing.JFrame implements ActionListener {





    /**
     * Creates new form login
     */
    public Mains() {
        initComponents();
        currentTime();
        CurrentDate();
        setLocationRelativeTo(null);
          setIconImage(new ImageIcon("E:\\Documents\\Computer Programing\\Java\\Church Managements System 3\\src\\ICONS\\Church-icon 2.png").getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblhome = new javax.swing.JLabel();
        lblopenanewapp = new javax.swing.JLabel();
        lblnews = new javax.swing.JLabel();
        lblprint = new javax.swing.JLabel();
        lblexecutives = new javax.swing.JLabel();
        lblrecords = new javax.swing.JLabel();
        lbltithe = new javax.swing.JLabel();
        lblsearch = new javax.swing.JLabel();
        lbladdmember = new javax.swing.JLabel();
        lbladdnew = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblTotalmember = new javax.swing.JLabel();
        lbldeads = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblmale = new javax.swing.JLabel();
        lblfemale = new javax.swing.JLabel();
        lblchildren = new javax.swing.JLabel();
        lbladults = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableViewAllMembers = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jfiles = new javax.swing.JMenu();
        jedit = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jtime1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jdate = new javax.swing.JMenu();
        jtime = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Group 9 Church Management App");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 0, 102));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Total Member Lists");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(371, 371, 371)
                .addComponent(jLabel8)
                .addContainerGap(516, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 20));

        jPanel2.setBackground(new java.awt.Color(51, 0, 102));

        lblhome.setForeground(new java.awt.Color(255, 255, 255));
        lblhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new_/icons8_home_30px_2.png"))); // NOI18N
        lblhome.setText("     Home");
        lblhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblhomeMouseClicked(evt);
            }
        });

        lblopenanewapp.setForeground(new java.awt.Color(255, 255, 255));
        lblopenanewapp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new_/icons8_linux_filled_30px.png"))); // NOI18N
        lblopenanewapp.setText("Open Presentation");
        lblopenanewapp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblopenanewappMouseClicked(evt);
            }
        });

        lblnews.setForeground(new java.awt.Color(255, 255, 255));
        lblnews.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new_/icons8_worldwide_location_30px.png"))); // NOI18N
        lblnews.setText("     Read News");
        lblnews.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblnewsMouseClicked(evt);
            }
        });

        lblprint.setForeground(new java.awt.Color(255, 255, 255));
        lblprint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new_/icons8_pdf_30px_2.png"))); // NOI18N
        lblprint.setText("     Print Records");
        lblprint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblprintMouseClicked(evt);
            }
        });

        lblexecutives.setForeground(new java.awt.Color(255, 255, 255));
        lblexecutives.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new_/icons8_meeting_30px_1.png"))); // NOI18N
        lblexecutives.setText("     Church Executives");
        lblexecutives.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblexecutivesMouseClicked(evt);
            }
        });

        lblrecords.setForeground(new java.awt.Color(255, 255, 255));
        lblrecords.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new_/icons8_cashflow_filled_30px.png"))); // NOI18N
        lblrecords.setText("     View Tithe Records");
        lblrecords.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblrecordsMouseClicked(evt);
            }
        });

        lbltithe.setForeground(new java.awt.Color(255, 255, 255));
        lbltithe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new_/icons8_money_bag_30px_1.png"))); // NOI18N
        lbltithe.setText("     Tithe & Offerings");
        lbltithe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbltitheMouseClicked(evt);
            }
        });

        lblsearch.setForeground(new java.awt.Color(255, 255, 255));
        lblsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new_/icons8_search_30px_1.png"))); // NOI18N
        lblsearch.setText("     Search Member");
        lblsearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblsearchMouseClicked(evt);
            }
        });

        lbladdmember.setForeground(new java.awt.Color(255, 255, 255));
        lbladdmember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new_/icons8_business_contact_30px_1.png"))); // NOI18N
        lbladdmember.setText("     Add member Details");
        lbladdmember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbladdmemberMouseClicked(evt);
            }
        });

        lbladdnew.setForeground(new java.awt.Color(255, 255, 255));
        lbladdnew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new_/icons8_add_user_group_man_man_30px_1.png"))); // NOI18N
        lbladdnew.setText("     Add Member");
        lbladdnew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbladdnewMouseClicked(evt);
            }
        });

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new_/Knob-Cancel-icon.png"))); // NOI18N
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Try me");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblhome)
                    .addComponent(lblopenanewapp)
                    .addComponent(lblnews)
                    .addComponent(lblprint)
                    .addComponent(lblexecutives)
                    .addComponent(lblrecords)
                    .addComponent(lbltithe)
                    .addComponent(lblsearch)
                    .addComponent(lbladdmember)
                    .addComponent(lbladdnew))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblhome)
                .addGap(18, 18, 18)
                .addComponent(lbladdnew)
                .addGap(18, 18, 18)
                .addComponent(lbladdmember)
                .addGap(18, 18, 18)
                .addComponent(lblsearch)
                .addGap(18, 18, 18)
                .addComponent(lbltithe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblrecords)
                .addGap(25, 25, 25)
                .addComponent(lblexecutives)
                .addGap(18, 18, 18)
                .addComponent(lblprint)
                .addGap(18, 18, 18)
                .addComponent(lblnews)
                .addGap(18, 18, 18)
                .addComponent(lblopenanewapp)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel22))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)))
                .addGap(146, 146, 146))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 190, 540));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new_/Knob-Cancel-icon.png"))); // NOI18N
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 520, -1, -1));

        jPanel3.setBackground(new java.awt.Color(204, 0, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setForeground(new java.awt.Color(204, 0, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, 10, 540));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new_/church total2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 20, 150, 130));

        lblTotalmember.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblTotalmember.setForeground(new java.awt.Color(0, 51, 255));
        lblTotalmember.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalmember.setText("0");
        lblTotalmember.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Total Members", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 153, 255))); // NOI18N
        getContentPane().add(lblTotalmember, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 150, 220, 80));

        lbldeads.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbldeads.setForeground(new java.awt.Color(255, 0, 51));
        lbldeads.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbldeads.setText("0");
        getContentPane().add(lbldeads, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 500, 120, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new_/man.png"))); // NOI18N
        jLabel3.setText("Male");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 240, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new_/woman.png"))); // NOI18N
        jLabel4.setText("Female");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 300, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new_/child.png"))); // NOI18N
        jLabel5.setText("Children");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 360, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new_/aduld.png"))); // NOI18N
        jLabel6.setText(" Adults");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 420, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new_/dead.png"))); // NOI18N
        jLabel2.setText(" Dead");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 490, -1, -1));

        lblmale.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblmale.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblmale.setText("0");
        getContentPane().add(lblmale, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 250, 120, 30));

        lblfemale.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblfemale.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblfemale.setText("0");
        getContentPane().add(lblfemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 310, 120, 30));

        lblchildren.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblchildren.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblchildren.setText("0");
        getContentPane().add(lblchildren, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 370, 120, 30));

        lbladults.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbladults.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbladults.setText("0");
        getContentPane().add(lbladults, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 430, 120, 30));

        TableViewAllMembers.setBackground(new java.awt.Color(0, 153, 255));
        TableViewAllMembers.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TableViewAllMembers.setForeground(new java.awt.Color(255, 255, 255));
        TableViewAllMembers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TableViewAllMembers);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 17, 570, 540));

        jfiles.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Home", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 255))); // NOI18N
        jfiles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/icons8_Home_48px_1.png"))); // NOI18N
        jfiles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jfilesMouseClicked(evt);
            }
        });
        jfiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfilesActionPerformed(evt);
            }
        });
        jfiles.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jfilesKeyPressed(evt);
            }
        });
        jMenuBar1.add(jfiles);

        jedit.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Update", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 255))); // NOI18N
        jedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new_/icons8_view_file_50px.png"))); // NOI18N
        jedit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jeditMouseClicked(evt);
            }
        });
        jMenuBar1.add(jedit);

        jMenu1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Printer", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 102, 255))); // NOI18N
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new_/icons8_pdf_50px.png"))); // NOI18N
        jMenuBar1.add(jMenu1);

        jtime1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Activities", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 255))); // NOI18N
        jtime1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new_/Activity-Monitor-icon.png"))); // NOI18N
        jtime1.setFocusable(false);
        jtime1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jtime1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtime1MouseClicked(evt);
            }
        });
        jtime1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtime1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jtime1);

        jMenu3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Eve", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 102, 255))); // NOI18N
        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new_/add-event-icon.png"))); // NOI18N
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Calculator", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 102, 255))); // NOI18N
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new_/icons8_calculator_50px_1.png"))); // NOI18N
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Easy", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 102, 255))); // NOI18N
        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new_/EasyWorship_www.tunacionpc.org-removebg-preview.png"))); // NOI18N
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jdate.setBorder(null);
        jdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Calendar_48px.png"))); // NOI18N
        jdate.setFocusable(false);
        jdate.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jdateMouseClicked(evt);
            }
        });
        jMenuBar1.add(jdate);

        jtime.setBorder(null);
        jtime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new_/icons8_Alarm_Clock_48px.png"))); // NOI18N
        jtime.setFocusable(false);
        jtime.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jtime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtimeMouseClicked(evt);
            }
        });
        jMenuBar1.add(jtime);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
        public void currentTime() {
        //cut this code as i do look
       
          Thread clock = new Thread(){
              public void run(){
                  for(;;){
                      Calendar cal = new GregorianCalendar();
        int second = cal.get(Calendar.SECOND);
         int munite  = cal.get(Calendar.MINUTE);
          int hour = cal.get(Calendar.HOUR);
           int AM_PM = cal.get(Calendar.AM_PM);
           String day_night = "";
           if(AM_PM == 1)
                  {
                    day_night = "PM";  
                  }
           else
                  {
                      day_night = "AM";
                  }
          jtime.setText(" :: "+hour+" : "+munite+" : "+second+" "+day_night );
                     try{
                       sleep(1000);  
                     }catch (Exception e){
                         JOptionPane.showMessageDialog(null, e);
                     }
                  }
              }
          };
          clock.start();
    }
    private void lblhomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhomeMouseClicked
 JOptionPane.showMessageDialog(null, "Be alert!!\n\n You Are heading HOME");  
        
    }//GEN-LAST:event_lblhomeMouseClicked

    private void lbladdmemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbladdmemberMouseClicked
        // TODO add your handling code here:
        new Update_Member().setVisible(true);
           dispose();
        
        
    }//GEN-LAST:event_lbladdmemberMouseClicked

    private void lblsearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsearchMouseClicked
        // TODO add your handling code here:
        new New_member().setVisible(true);
           //dispose();
    }//GEN-LAST:event_lblsearchMouseClicked

    private void lblexecutivesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblexecutivesMouseClicked
        // TODO add your handling code here:
        new Church_Executives().setVisible(true);
           //dispose();
    }//GEN-LAST:event_lblexecutivesMouseClicked

    private void lbltitheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbltitheMouseClicked
        // TODO add your handling code here:
        new Tithes().setVisible(true);
           //dispose();
    }//GEN-LAST:event_lbltitheMouseClicked

    private void lbladdnewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbladdnewMouseClicked
        // TODO add your handling code here:
        new New_member().setVisible(true);
           //dispose();
    }//GEN-LAST:event_lbladdnewMouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        // TODO add your handling code here:
          int dialogResult=JOptionPane.showConfirmDialog(null, "Hello!!, You have decided to CLOSE this program","Warning",JOptionPane.YES_NO_OPTION);
        if(dialogResult  == JOptionPane.YES_OPTION)
        {

            this.dispose();
        }
    }//GEN-LAST:event_jLabel22MouseClicked

    private void lblnewsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblnewsMouseClicked
        // TODO add your handling code here:
        String url;
        url = "www.Google.com";
        try {
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
        } catch (IOException ex) {
            Logger.getLogger(Mains.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblnewsMouseClicked

    private void lblprintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblprintMouseClicked
        // TODO add your handling code here:
        new Registered_table().setVisible(true);
           
    }//GEN-LAST:event_lblprintMouseClicked

    private void jfilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfilesActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Don't Be Confused!!\n\n You Are Already HOME");
    }//GEN-LAST:event_jfilesActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
        new Calculator().setVisible(true);
        
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jtime1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtime1ActionPerformed
        // TODO add your handling code here:
        new church_activities().setVisible(true);
        
    }//GEN-LAST:event_jtime1ActionPerformed

    private void jfilesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jfilesKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfilesKeyPressed

    private void jfilesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jfilesMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Don't Be Confused!!\n\n You Are Already HOME");
    }//GEN-LAST:event_jfilesMouseClicked

    private void jtime1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtime1MouseClicked
        // TODO add your handling code here:
        new church_activities().setVisible(true);
    }//GEN-LAST:event_jtime1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        new Calculator().setVisible(true);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jdateMouseClicked
        // TODO add your handling code here:
        new Knowtheday().setVisible(true);
    }//GEN-LAST:event_jdateMouseClicked

    private void jtimeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtimeMouseClicked
        // TODO add your handling code here:
        new Clock().setVisible(true);
    }//GEN-LAST:event_jtimeMouseClicked

    private void lblopenanewappMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblopenanewappMouseClicked
    int dialogResult=JOptionPane.showConfirmDialog(null, "Hello!!, You are about to open EAZYWOERSHIP 6 FOR CHURCH\n\n\n Are you sure you want to do this??"," Operator Warning",JOptionPane.YES_NO_OPTION);
        if(dialogResult  == JOptionPane.YES_OPTION)
        {

            Runtime runtime = Runtime.getRuntime();     //getting Runtime object
 
        String[] s = new String[] {"C:\\Program Files (x86)\\Softouch\\Easyworship 6\\Easyworship.exe"};
 
        try
        {
            runtime.exec(s);        //This opens the application
        }
        catch (IOException e)
        {
            e.printStackTrace();
        } 
  
        }
        
        
        
    }//GEN-LAST:event_lblopenanewappMouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        new Add_Event().setVisible(true);
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jeditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jeditMouseClicked
        // TODO add your handling code here:
        new Update_Member().setVisible(true);
    }//GEN-LAST:event_jeditMouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
        
        int dialogResult=JOptionPane.showConfirmDialog(null, "Hello!!, You are about to open EAZYWOERSHIP 6 FOR CHURCH\n\n\n Are you sure you want to do this??"," Operator Warning",JOptionPane.YES_NO_OPTION);
        if(dialogResult  == JOptionPane.YES_OPTION)
        {

            Runtime runtime = Runtime.getRuntime();     //getting Runtime object
 
        String[] s = new String[] {"C:\\Program Files (x86)\\Softouch\\Easyworship 6\\Easyworship.exe"};
 
        try
        {
            runtime.exec(s);        //This opens the application
        }
        catch (IOException e)
        {
            e.printStackTrace();
        } 
  
        }
        
        
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        // TODO add your handling code here:
         int dialogResult=JOptionPane.showConfirmDialog(null, "Hello!!, You have decided to CLOSE this program","Warning",JOptionPane.YES_NO_OPTION);
        if(dialogResult  == JOptionPane.YES_OPTION)
        {

            this.dispose();
        }
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        New_member frm = new New_member();
        frm.show();
        
    }//GEN-LAST:event_jLabel7MouseClicked

    private void lblrecordsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblrecordsMouseClicked
        // TODO add your handling code here:
        new View_Tithe_Records().setVisible(true);
    }//GEN-LAST:event_lblrecordsMouseClicked

      public void CurrentDate(){
          Calendar cal = new GregorianCalendar();
        int year = cal.get(Calendar.YEAR);
         int month  = cal.get(Calendar.MONTH);
          int day = cal.get(Calendar.DAY_OF_MONTH);
        String Date;
          jdate.setText(" :: " + day+" - "+(month+1)+" - "+year);
           try{
                       sleep(1000);  
                     }catch (Exception e){
                         JOptionPane.showMessageDialog(null, e);
                     }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
              
        UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mains().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableViewAllMembers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenu jdate;
    private javax.swing.JMenu jedit;
    private javax.swing.JMenu jfiles;
    private javax.swing.JMenu jtime;
    private javax.swing.JMenu jtime1;
    private javax.swing.JLabel lblTotalmember;
    private javax.swing.JLabel lbladdmember;
    private javax.swing.JLabel lbladdnew;
    private javax.swing.JLabel lbladults;
    private javax.swing.JLabel lblchildren;
    private javax.swing.JLabel lbldeads;
    private javax.swing.JLabel lblexecutives;
    private javax.swing.JLabel lblfemale;
    private javax.swing.JLabel lblhome;
    private javax.swing.JLabel lblmale;
    private javax.swing.JLabel lblnews;
    private javax.swing.JLabel lblopenanewapp;
    private javax.swing.JLabel lblprint;
    private javax.swing.JLabel lblrecords;
    private javax.swing.JLabel lblsearch;
    private javax.swing.JLabel lbltithe;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent ae) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
