
package log;

import java.awt.Image;
import javax.swing.JFileChooser;
import javax.swing.ImageIcon;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author EstyLand
 */
public class Update_Member extends javax.swing.JFrame {

    
    String imagePath;
    File f;
    /**
     * Creates new form Update_Member
     */
    
    
    
    
    public Update_Member() {
        setLocationRelativeTo(null);
        initComponents();
        setIconImage(new ImageIcon("E:\\Documents\\Computer Programing\\Java\\Church Managements System 3\\src\\Mmber\\icons8_approve_and_update_30px.png").getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtnameoffather = new javax.swing.JTextField();
        txtnameofmother = new javax.swing.JTextField();
        txtpreviousreligion = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtcurrentdateofbaptism = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtplaceofbaptism = new javax.swing.JTextField();
        txtbaptisedby = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtoccupationalbackground = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txteducationallevel = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        cmbconversionmethod = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        cmbmembershipstand = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        cmbtotalweek = new javax.swing.JComboBox<>();
        cmbweek1 = new javax.swing.JComboBox<>();
        cmbweek2 = new javax.swing.JComboBox<>();
        cmbweek3 = new javax.swing.JComboBox<>();
        cmbweek4 = new javax.swing.JComboBox<>();
        txtPostalAddress = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtPlaceOfResidence = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtSurname = new javax.swing.JTextField();
        txtChristianName = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtOtherName = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbSex = new javax.swing.JComboBox<>();
        cmbmarital = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtNameOfSpouse = new javax.swing.JTextField();
        txtNumberOfDependant = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jButtonprint3 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btnBrowse = new javax.swing.JButton();
        lblPassportPicture = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Date_txt = new javax.swing.JLabel();
        lbltime = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnview = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mmber/icons8_whatsapp_20px_2.png"))); // NOI18N
        jLabel8.setText("Contacts:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, 26));
        getContentPane().add(txtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 190, -1));

        jLabel9.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mmber/icons8_mailbox_with_letter_20px_1.png"))); // NOI18N
        jLabel9.setText("Postal Address:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, 26));

        jPanel5.setBackground(new java.awt.Color(153, 204, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Stand/icons8_man_face_20px.png"))); // NOI18N
        jLabel15.setText("Name of the Father:");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 151, 26));

        jLabel16.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Stand/icons8_breastfeeding_20px.png"))); // NOI18N
        jLabel16.setText("Name of the Mother:");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 183, 26));

        jLabel19.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Stand/icons8_hanukkah_20px_1.png"))); // NOI18N
        jLabel19.setText("Previous Religion");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 183, 26));

        txtnameoffather.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameoffatherActionPerformed(evt);
            }
        });
        jPanel5.add(txtnameoffather, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 168, -1));
        jPanel5.add(txtnameofmother, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 168, -1));

        txtpreviousreligion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpreviousreligionActionPerformed(evt);
            }
        });
        jPanel5.add(txtpreviousreligion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 168, -1));

        jLabel20.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Stand/icons8_overtime_20px.png"))); // NOI18N
        jLabel20.setText(" Date of Baptism");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 183, 26));

        txtcurrentdateofbaptism.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcurrentdateofbaptismActionPerformed(evt);
            }
        });
        jPanel5.add(txtcurrentdateofbaptism, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 168, -1));

        jLabel21.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Stand/icons8_point_objects_20px_1.png"))); // NOI18N
        jLabel21.setText("Place of Baptism");
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 183, 26));

        txtplaceofbaptism.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtplaceofbaptismActionPerformed(evt);
            }
        });
        jPanel5.add(txtplaceofbaptism, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 168, -1));

        txtbaptisedby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbaptisedbyActionPerformed(evt);
            }
        });
        jPanel5.add(txtbaptisedby, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 168, -1));

        jLabel22.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Stand/icons8_priest_20px.png"))); // NOI18N
        jLabel22.setText("Baptised by");
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, 26));
        jPanel5.add(txtoccupationalbackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 168, -1));

        jLabel23.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Stand/icons8_permanent_job_20px.png"))); // NOI18N
        jLabel23.setText("Occupation");
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, 26));

        txteducationallevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txteducationallevelActionPerformed(evt);
            }
        });
        jPanel5.add(txteducationallevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 168, -1));

        jLabel24.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Stand/icons8_student_male_20px.png"))); // NOI18N
        jLabel24.setText("Educational");
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, 26));

        jLabel25.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Stand/icons8_won_opportunity_20px.png"))); // NOI18N
        jLabel25.setText("Conversion Method");
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, 26));

        cmbconversionmethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Through :", "Envagelism", "Self-Willing", "Afriend's Invitation", " Birth", "Marriage" }));
        cmbconversionmethod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbconversionmethodActionPerformed(evt);
            }
        });
        jPanel5.add(cmbconversionmethod, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 168, -1));

        jLabel26.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Stand/icons8_standing_woman_20px.png"))); // NOI18N
        jLabel26.setText("Membership Stand");
        jPanel5.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 151, 26));

        cmbmembershipstand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Good", "Not", " " }));
        cmbmembershipstand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbmembershipstandActionPerformed(evt);
            }
        });
        jPanel5.add(cmbmembershipstand, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 168, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not in a good stand", "Reasons:", "Date of Suspension....", "Date of reinstatement...." }));
        jPanel5.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 168, -1));

        jLabel27.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Stand/icons8_attendance_mark_20px.png"))); // NOI18N
        jLabel27.setText("Attendance");
        jPanel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, 26));

        cmbtotalweek.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Total Week In The Month", "0", "1", "2", "3", "4", " " }));
        jPanel5.add(cmbtotalweek, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 170, -1));

        cmbweek1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Week 1-", "Present", "Absent" }));
        jPanel5.add(cmbweek1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, -1, -1));

        cmbweek2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Week 2-", "Present", "Absent" }));
        jPanel5.add(cmbweek2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 70, -1));

        cmbweek3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Week 3-", "Present", "Absent" }));
        jPanel5.add(cmbweek3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, -1, -1));

        cmbweek4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Week 4-", "Present", "Absent" }));
        jPanel5.add(cmbweek4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 70, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 68, 440, 510));
        getContentPane().add(txtPostalAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 190, -1));

        jLabel10.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mmber/icons8_marker_20px.png"))); // NOI18N
        jLabel10.setText("Residence:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, 26));
        getContentPane().add(txtPlaceOfResidence, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 424, 190, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mmber/icons8_outgoing_call_20px.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        jScrollPane1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 233, 310, 450));

        jLabel11.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mmber/icons8_marker_20px.png"))); // NOI18N
        jLabel11.setText("Email:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, 26));

        jLabel2.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mmber/icons8_name_20px.png"))); // NOI18N
        jLabel2.setText("SurName:");

        txtSurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSurnameActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mmber/icons8_christmas_star_20px.png"))); // NOI18N
        jLabel17.setText("ChristianName:");

        jLabel18.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mmber/icons8_mothers_health_20px.png"))); // NOI18N
        jLabel18.setText("OtherName:");

        txtOtherName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOtherNameActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mmber/icons8_baby_20px.png"))); // NOI18N
        jLabel5.setText("Date Of Birth:");

        jLabel4.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mmber/icons8_toilet_20px.png"))); // NOI18N
        jLabel4.setText("Sex:");

        cmbSex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select-", "Male", "Female" }));
        cmbSex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSexActionPerformed(evt);
            }
        });

        cmbmarital.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Marital Status-", "Single", "Married", "Divorced" }));
        cmbmarital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbmaritalActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mmber/icons8_date_20px.png"))); // NOI18N
        jLabel12.setText("Marrital Status:");

        jLabel13.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mmber/icons8_groom_20px.png"))); // NOI18N
        jLabel13.setText("Name of Spouse:");

        jLabel14.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mmber/icons8_family_two_men_20px.png"))); // NOI18N
        jLabel14.setText("Dependent:");

        jLabel3.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mmber/icons8_id_verified_20px.png"))); // NOI18N
        jLabel3.setText("ID");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(79, 79, 79)
                        .addComponent(cmbSex, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNameOfSpouse, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(txtNumberOfDependant)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbmarital, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtOtherName)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel17)
                                .addGap(10, 10, 10)
                                .addComponent(txtChristianName, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(3, 3, 3)))
                .addGap(29, 29, 29))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtChristianName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOtherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbmarital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNameOfSpouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumberOfDependant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 360, 304));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 454, 190, -1));

        jButtonprint3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Stand/icons8_pdf_2_20px.png"))); // NOI18N
        jButtonprint3.setText("Print");
        jButtonprint3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonprint3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonprint3, new org.netbeans.lib.awtextra.AbsoluteConstraints(765, 633, -1, 50));

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Stand/icons8_cancel_2_20px.png"))); // NOI18N
        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 623, -1, 60));

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Stand/icons8_synchronize_20px.png"))); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 623, -1, 60));

        btnupdate.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mmber/icons8_approve_and_update_30px.png"))); // NOI18N
        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 623, -1, 60));

        btnBrowse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Stand/icons8_user_folder_30px.png"))); // NOI18N
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });
        getContentPane().add(btnBrowse, new org.netbeans.lib.awtextra.AbsoluteConstraints(879, 123, -1, 60));

        lblPassportPicture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPassportPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Stand/Office-Customer-Male-Light-icon.png"))); // NOI18N
        getContentPane().add(lblPassportPicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(942, 53, 220, 170));

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel1.setText("CHURCH MEMBERSHIP SYSTEM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jLabel1)
                .addContainerGap(177, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Date_txt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Date_txt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Stand/icons8_planner_30px_1.png"))); // NOI18N

        lbltime.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        lbltime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Stand/icons8_alarm_clock_30px.png"))); // NOI18N

        txtID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtID.setForeground(new java.awt.Color(0, 153, 255));
        txtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIDKeyTyped(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mmber/icons8_search_20px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(922, 922, 922)
                .addComponent(jSeparator1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127)
                .addComponent(Date_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbltime, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Date_txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbltime, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1150, 50));

        btnview.setBackground(new java.awt.Color(255, 255, 0));
        btnview.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Stand/icons8_visible_20px.png"))); // NOI18N
        btnview.setText("view");
        getContentPane().add(btnview, new org.netbeans.lib.awtextra.AbsoluteConstraints(762, 584, 82, 43));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtnameoffatherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameoffatherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameoffatherActionPerformed

    private void txtpreviousreligionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpreviousreligionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpreviousreligionActionPerformed

    private void txtcurrentdateofbaptismActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcurrentdateofbaptismActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcurrentdateofbaptismActionPerformed

    private void txtplaceofbaptismActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtplaceofbaptismActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtplaceofbaptismActionPerformed

    private void txtbaptisedbyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbaptisedbyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbaptisedbyActionPerformed

    private void txteducationallevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txteducationallevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txteducationallevelActionPerformed

    private void cmbconversionmethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbconversionmethodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbconversionmethodActionPerformed

    private void cmbmembershipstandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbmembershipstandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbmembershipstandActionPerformed

    private void txtSurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSurnameActionPerformed

    private void txtOtherNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOtherNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOtherNameActionPerformed

    private void cmbSexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSexActionPerformed

    private void cmbmaritalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbmaritalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbmaritalActionPerformed

    private void jButtonprint3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonprint3ActionPerformed
        try{
            boolean complete= jTextArea1.print();

            if(complete){
                JOptionPane.showMessageDialog(this,"PRINTING SUCCESSFUL","",INFORMATION_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(this,"EXIT PRINTER !","",ERROR_MESSAGE);
            }
        }
        catch(Exception e){

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonprint3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //new Decision_Board().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        /* public void resetMethod() {
            txtName.setText(null);
            jTextField10.setText(null);
            jTextField11.setText(null);
            jTextField12.setText(null);
            jTextField2.setText(null);
            jTextField3.setText(null);
            jTextField4.setText(null);
            jTextField5.setText(null);
            jTextField6.setText(null);
            jTextField7.setText(null);
            jTextField8.setText(null);
            jTextField9.setText(null);
            picturess.setText(null);
            cmbDay.setSelectedIndex(0);
            cmbMonth.setSelectedIndex(0);
            cmbYear.setSelectedIndex(0);
        } */

        reset();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        String id = txtID.getText();
        String surname = txtSurname.getText();
        String christianname = txtChristianName .getText();
        String othername = txtOtherName.getText();
        String sex = cmbSex.getSelectedItem().toString();
        String contact = txtContact.getText();
        String postaladdress = txtPostalAddress.getText();
        String placeofresidence = txtPlaceOfResidence.getText();
        //String maritalstatus = txtMaritalStatus.getText();
        String nameofspouse = txtNameOfSpouse.getText();
        String numberofdependent = txtNumberOfDependant.getText();
        String emailaddress = txtEmail.getText();
        //String day = cmbDay.getSelectedItem().toString();
        //// String month = cmbMonth.getSelectedItem().toString();
        //String year1 = cmbYear.getSelectedItem().toString();

        String sql = "insert into membersregistration values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

       
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        //        JFileChooser pic = new JFileChooser();
        //        int a = pic.showOpenDialog(this);
        //        if(a==JFileChooser.APPROVE_OPTION)
        //        f=pic.getSelectedFile();
        //        Image img=getToolkit().createImage(f.getAbsolutePath());
        //        img = img.getScaledInstance(259, 275, Image.SCALE_SMOOTH);
        //        lblPassportPicture.setIcon(new ImageIcon(img));

        browseAction();
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void txtIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyTyped
        // TODO add your handling code here:
        String id = txtID.getText();

        String sql = "select * from membersregistration where id = ?";

        try {

            Connection con = new Database().connect();
            PreparedStatement ps = con.prepareStatement(sql);

            ps.setString(1, id);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {

                String surname = rs.getString(2);
                String christianname = rs.getString(3);
                String othername = rs.getString(4);
                String sex = rs.getString(5);
                String contact = rs.getString(6);
                String postaladdress = rs.getString(7);
                String placeofresidence = rs.getString(8);
                String maritalstatus = rs.getString(9);
                String nameofspouse = rs.getString(10);
                String numberofdependent = rs.getString(11);
                String emailaddress = rs.getString(12);
                String day = rs.getString(13);
                String month = rs.getString(14);
                String year1 = rs.getString(15);

                txtSurname.setText(surname);
                txtChristianName.setText(christianname);
                txtOtherName.setText(othername);
                //cmbDay.setSelectedItem(day);
                //cmbMonth.setSelectedItem(month);
                // cmbYear.setSelectedItem(year1);
                cmbSex.setSelectedItem(sex);
                txtContact.setText(contact);
                txtPostalAddress.setText(postaladdress);
                txtPlaceOfResidence.setText(placeofresidence);
                //txtMaritalStatus.setText(maritalstatus);
                txtNameOfSpouse.setText( nameofspouse);
                txtNumberOfDependant.setText(numberofdependent);
                txtEmail.setText(emailaddress);
                lblPassportPicture.setIcon(null);
                byte[] imageByte = rs.getBytes(16);
                Image img = null;
                if(imageByte != null) {
                    img = new JFrame().getToolkit().createImage(imageByte);
                    ImageIcon icon = new ImageIcon(img);
                    img = TeaImage.getScaledImage(icon.getImage(), 266, 266);
                    icon = new ImageIcon(img);
                    lblPassportPicture.setIcon(icon);
                } else {
                    lblPassportPicture.setIcon(null);
                }

            } else {
                JOptionPane.showMessageDialog(this, "Members ID Not Found");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Search_a_member.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_txtIDKeyTyped

     private void browseAction() {
        JFileChooser fc = new JFileChooser();
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("Image file", "jpg",
        "png", "jpeg", "tiff");
        fc.setFileFilter(fnef);
        
         if(fc.showOpenDialog(this)== JFileChooser.APPROVE_OPTION){
            imagePath = fc.getSelectedFile().getPath();
            ImageIcon img = TeaImage.getImageIcon(imagePath);
            img = new ImageIcon(TeaImage.getScaledImage(img.getImage(), 266));
      
            lblPassportPicture.setIcon(img);
        } 
    }    public void reset() {
        txtID.setText(null);
        txtSurname.setText(null);
        txtChristianName.setText(null);
        txtOtherName.setText(null);
    txtEmail.setText(null);
 
  txtContact.setText(null);
   txtPostalAddress.setText(null);
     txtPlaceOfResidence.setText(null);
     //txtMaritalStatus.setText(null);
   txtNameOfSpouse.setText(null);
   jTextArea1.setText(null);
   txtNumberOfDependant.setText(null);
     lblPassportPicture.setText(null);
     //cmbDay.setSelectedIndex(0);
     //cmbMonth.setSelectedIndex(0);
    //cmbYear.setSelectedIndex(0);
    cmbSex.setSelectedIndex(0);
    lblPassportPicture.setIcon(null);
 }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update_Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update_Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update_Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update_Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update_Member().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Date_txt;
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnupdate;
    private javax.swing.JButton btnview;
    private javax.swing.JComboBox<String> cmbSex;
    private javax.swing.JComboBox<String> cmbconversionmethod;
    private javax.swing.JComboBox<String> cmbmarital;
    private javax.swing.JComboBox<String> cmbmembershipstand;
    private javax.swing.JComboBox<String> cmbtotalweek;
    private javax.swing.JComboBox<String> cmbweek1;
    private javax.swing.JComboBox<String> cmbweek2;
    private javax.swing.JComboBox<String> cmbweek3;
    private javax.swing.JComboBox<String> cmbweek4;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonprint3;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblPassportPicture;
    private javax.swing.JLabel lbltime;
    private javax.swing.JTextField txtChristianName;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNameOfSpouse;
    private javax.swing.JTextField txtNumberOfDependant;
    private javax.swing.JTextField txtOtherName;
    private javax.swing.JTextField txtPlaceOfResidence;
    private javax.swing.JTextField txtPostalAddress;
    private javax.swing.JTextField txtSurname;
    private javax.swing.JTextField txtbaptisedby;
    private javax.swing.JTextField txtcurrentdateofbaptism;
    private javax.swing.JTextField txteducationallevel;
    private javax.swing.JTextField txtnameoffather;
    private javax.swing.JTextField txtnameofmother;
    private javax.swing.JTextField txtoccupationalbackground;
    private javax.swing.JTextField txtplaceofbaptism;
    private javax.swing.JTextField txtpreviousreligion;
    // End of variables declaration//GEN-END:variables
}
