
package log;

import java.io.File;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

public class View_Tithe_Records extends javax.swing.JFrame {
 
 
    public View_Tithe_Records() {
        //CurrentDate();
        initComponents();
        setLocationRelativeTo(null);
         setIconImage(new ImageIcon("E:\\Documents\\Computer Programing\\Java\\Church Managements System 3\\src\\new_\\Dollar-icon.png").getImage());
         
    }

    
//     public void CurrentDate(){
//          Calendar cal = new GregorianCalendar();
//        int year = cal.get(Calendar.YEAR);
//         int month  = cal.get(Calendar.MONTH);
//          int day = cal.get(Calendar.DAY_OF_MONTH);
//        String Date;
//          lbldate.setText("  " + day+" / "+(month+1)+" / "+year);
//           try{
//                       sleep(1000);  
//                     }catch (Exception e){
//                         JOptionPane.showMessageDialog(null, e);
//                     }
//    
//     }
//    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        btnend = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        lbldate = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        btnupdate = new javax.swing.JButton();
        btnprint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Individual Tithe View");
        setForeground(new java.awt.Color(102, 153, 255));
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 237, 420, 11));

        btnend.setBackground(new java.awt.Color(51, 204, 255));
        btnend.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tithe/icons8_shutdown_30px.png"))); // NOI18N
        btnend.setText("End");
        btnend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnendActionPerformed(evt);
            }
        });
        getContentPane().add(btnend, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, 90, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tithe/icons8_id_verified_30px_1.png"))); // NOI18N
        jLabel1.setText("Member ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 34, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tithe/icons8_name_30px.png"))); // NOI18N
        jLabel2.setText("Name ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 82, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tithe/icons8_planner_30px.png"))); // NOI18N
        jLabel3.setText("Date");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 189, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tithe/icons8_receive_cash_30px_2.png"))); // NOI18N
        jLabel4.setText("Tithe Amount");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 141, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tithe/icons8_week_view_30px.png"))); // NOI18N
        jLabel5.setText("Total Weekly");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tithe/icons8_total_sales_1_30px_2.png"))); // NOI18N
        jLabel6.setText("Total Monthly");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 298, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tithe/icons8_sigma_30px.png"))); // NOI18N
        jLabel7.setText("Total Yearly");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 348, -1, -1));

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(102, 102, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("0");
        jTextField1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 32, 265, 30));

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(102, 102, 255));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 83, 265, 29));

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(102, 102, 255));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("0");
        jTextField3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 138, 265, 28));

        lbldate.setEditable(false);
        lbldate.setFont(new java.awt.Font("Poor Richard", 0, 18)); // NOI18N
        lbldate.setForeground(new java.awt.Color(51, 51, 51));
        lbldate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lbldate.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        lbldate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbldateMouseClicked(evt);
            }
        });
        getContentPane().add(lbldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 189, 265, 27));

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 204, 0));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("0");
        jTextField5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 250, 265, 29));

        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(0, 204, 102));
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText("0");
        jTextField6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 298, 265, 29));

        jTextField7.setEditable(false);
        jTextField7.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(204, 0, 51));
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setText("0");
        jTextField7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 346, 265, 30));

        btnupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tithe/icons8_money_bag_30px_2.png"))); // NOI18N
        btnupdate.setText("Add");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 409, -1, 70));

        btnprint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tithe/icons8_printer_door_open_30px.png"))); // NOI18N
        btnprint.setText("Print");
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });
        getContentPane().add(btnprint, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 90, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnendActionPerformed
         //new Decision_Board().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnendActionPerformed

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed
        // TODO add your handling code here:
        new Registered_table().setVisible(true);
    }//GEN-LAST:event_btnprintActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        new Tithes().setVisible(true);
    }//GEN-LAST:event_btnupdateActionPerformed

    private void lbldateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldateMouseClicked
        // TODO add your handling code here:
        //lbldate.setText("12/12/2021");
        
    }//GEN-LAST:event_lbldateMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
      lbldate.setText("30/01/2021");
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Tithe_Records.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Tithe_Records.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Tithe_Records.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Tithe_Records.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
         UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_Tithe_Records().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnend;
    private javax.swing.JButton btnprint;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField lbldate;
    // End of variables declaration//GEN-END:variables
}
